SELECT A.AUTHOR_ID
     , MAX(C.AUTHOR_NAME) AS AUTHOR_NAME
     , A.CATEGORY
     , SUM(A.PRICE * B.SALES) AS TOTAL_SALES
  FROM BOOK  A
INNER JOIN (
    SELECT BOOK_ID
         , SUM(SALES) AS SALES
      FROM BOOK_SALES 
     WHERE YEAR(SALES_DATE) = '2022'
       AND MONTH(SALES_DATE) = '01'
      GROUP BY BOOK_ID
          ) B
    ON A.BOOK_ID = B.BOOK_ID
INNER JOIN AUTHOR  C
       ON A.AUTHOR_ID = C.AUTHOR_ID
     GROUP BY A.AUTHOR_ID, A.CATEGORY
     ORDER BY A.AUTHOR_ID, A.CATEGORY DESC