SELECT CART_ID
  FROM (
SELECT CART_ID, NAME
  FROM CART_PRODUCTS
 WHERE NAME IN ('Milk', 'Yogurt')
 GROUP BY NAME, CART_ID
      ) A
     GROUP BY CART_ID
     HAVING COUNT(1) > 1
     ORDER BY CART_ID