SELECT X.ID, X.LENGTH
  FROM (
select ROW_NUMBER() OVER (ORDER BY IFNULL(LENGTH, 10) DESC ) AS A_RANK
     , ID, IFNULL(LENGTH, 10) AS LENGTH
  from FISH_INFO
      ) X
     WHERE X.A_RANK <= 10
     ORDER BY X.A_RANK, X.ID