-- 코드를 입력하세요
SELECT *
  FROM (
SELECT MAX(A.PRODUCT_CODE) AS PRODUCT_CODE
     , SUM(B.SALES_AMOUNT * A.PRICE) AS SALES
  FROM PRODUCT A
  INNER JOIN OFFLINE_SALE B
     ON A.PRODUCT_ID = B.PRODUCT_ID
  GROUP BY B.PRODUCT_ID
   ) X
   ORDER BY X.SALES DESC, X.PRODUCT_CODE