-- 코드를 입력하세요
SELECT T.*
  FROM (
SELECT DATE_FORMAT(A.SALES_DATE, '%Y-%m-%d') AS SALES_DATE
     , A.PRODUCT_ID
     , A.USER_ID
     , A.SALES_AMOUNT
  FROM ONLINE_SALE  A
WHERE YEAR(A.SALES_DATE) = '2022'
  AND MONTH(A.SALES_DATE) = '03'
UNION ALL
SELECT DATE_FORMAT(X.SALES_DATE, '%Y-%m-%d')
     , X.PRODUCT_ID
     , NULL
     , X.SALES_AMOUNT
 FROM OFFLINE_SALE X 
WHERE YEAR(X.SALES_DATE) = '2022'
  AND MONTH(X.SALES_DATE) = '03'
  ) T
  ORDER BY T.SALES_DATE, T.PRODUCT_ID, T.USER_ID