
SELECT A.ANIMAL_ID
     , A.NAME
  FROM ANIMAL_INS  A
 INNER JOIN ANIMAL_OUTS B
   ON A.ANIMAL_ID = B.ANIMAL_ID
 WHERE DATEDIFF(B.DATETIME, A.DATETIME) > 0
  ORDER BY DATEDIFF(B.DATETIME, A.DATETIME) DESC 
  LIMIT 2
 