SELECT X.CAR_ID
     , X.CAR_TYPE
     , X.FEE
  FROM (
SELECT A.CAR_TYPE
     , A.CAR_ID
     , (A.DAILY_FEE * (1 - B.DISCOUNT_RATE/100)* 30)  AS FEE
  FROM CAR_RENTAL_COMPANY_CAR A
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B
   ON A.CAR_TYPE = B.CAR_TYPE
  AND B.DURATION_TYPE = '30일 이상'
INNER JOIN ( 
           SELECT X.CAR_ID
             FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY X
            GROUP BY X.CAR_ID
            HAVING TO_CHAR(MIN(X.START_DATE), 'YYYYMMDD') > '20221130' OR TO_CHAR(MAX(X.END_DATE), 'YYYYMMDD') < '20221101'
          ) C
    ON A.CAR_ID = C.CAR_ID
 WHERE A.CAR_TYPE IN ('세단', 'SUV')
 ) X
 WHERE X.FEE BETWEEN 500000 AND 2000000-1
  ORDER BY X.FEE DESC, X.CAR_TYPE, X.CAR_ID DESC