
SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE
  FROM (
SELECT ROW_NUMBER() OVER (ORDER BY PRICE DESC) AS RNUM 
    , PRODUCT_ID
    , PRODUCT_NAME
    , PRODUCT_CD
    , CATEGORY
    , PRICE
  FROM FOOD_PRODUCT 
 ) X
WHERE X.RNUM = 1