SELECT X.CAR_ID
     , X.AVG_DATE
  FROM (
SELECT CAR_ID
     , ROUND(SUM(DATEDIFF(END_DATE, START_DATE)+1) / COUNT(1), 1) AS AVG_DATE
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
 GROUP BY CAR_ID
      ) X
     WHERE X.AVG_DATE >= 7
    ORDER BY X.X.AVG_DATE DESC, X.CAR_ID DESC