
SELECT A.ROUTE
     , concat(ROUND(SUM(A.D_BETWEEN_DIST), 1), 'km') AS TOTAL_DISTANCE
     , concat(ROUND(AVG(A.D_BETWEEN_DIST), 2), 'km') AS AVERAGE_DISTANCE
  FROM SUBWAY_DISTANCE A
  GROUP BY A.ROUTE
  ORDER BY SUM(A.D_BETWEEN_DIST) DESC
