-- 코드를 입력하세요
SELECT A.NAME, A.DATETIME
  FROM ANIMAL_INS A
  WHERE NOT EXISTS (
            SELECT 1
              FROM ANIMAL_OUTS X
            WHERE A.ANIMAL_ID = X.ANIMAL_ID
  )
  ORDER BY A.DATETIME
  LIMIT 3