-- 코드를 입력하세요
SELECT A.PRODUCT_ID
     , B.PRODUCT_NAME
     , SUM(B.PRICE * A.AMOUNT) AS TOTAL_SALES
  FROM FOOD_ORDER A
 INNER JOIN FOOD_PRODUCT B
    ON A.PRODUCT_ID = B.PRODUCT_ID
 WHERE YEAR(A.PRODUCE_DATE) = '2022'
   AND MONTH(A.PRODUCE_DATE) = '05'
 GROUP BY A.PRODUCT_ID
 ORDER BY SUM(B.PRICE * A.AMOUNT) DESC, A.PRODUCT_ID
 
