SELECT B.HISTORY_ID
     , ROUND((A.DAILY_FEE * ( 1 - B.DISCOUTN_RATE)) * B.DIF_DATE, -1) AS FEE
  FROM CAR_RENTAL_COMPANY_CAR A
  INNER JOIN (
SELECT X.CAR_ID
     , X.HISTORY_ID
     , MAX(X.DIF_DATE) AS DIF_DATE
     , IFNULL(MAX(CASE WHEN X.DIF_DATE - T.DURATION >= 0 THEN DISCOUNT_RATE / 100 END), 0) AS  DISCOUTN_RATE
  FROM (
SELECT B.HISTORY_ID
     , B.CAR_ID
     , A.CAR_TYPE
     , DATEDIFF(B.END_DATE, B.START_DATE) + 1 AS DIF_DATE
  FROM CAR_RENTAL_COMPANY_CAR A
 INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
    ON A.CAR_ID = B.CAR_ID
 WHERE A.CAR_TYPE = '트럭'
      ) X
    INNER JOIN (
	           SELECT CAR_TYPE
                    , DISCOUNT_RATE
                    , REPLACE(DURATION_TYPE, '일 이상', '') AS DURATION
                 FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
			    ) T
      ON X.CAR_TYPE = T.CAR_TYPE
     GROUP BY X.HISTORY_ID, X.CAR_ID
      ) B
     ON A.CAR_ID = B.CAR_ID
ORDER BY 2 DESC, 1 DESC