WITH RECURSIVE CUSTOM_NUMBER AS (
     SELECT 0 AS RNUM
      UNION ALL
     SELECT RNUM + 1
      FROM CUSTOM_NUMBER
    WHERE RNUM < 23
)
SELECT A.RNUM AS HOUR
     , COUNT(HOUR(B.DATETIME)) AS COUNT
  FROM CUSTOM_NUMBER A
 LEFT OUTER JOIN ANIMAL_OUTS B
   ON A.RNUM = HOUR(B.DATETIME)
  GROUP BY A.RNUM
  ORDER BY A.RNUM