-- 코드를 입력하세요
SELECT X.USER_ID
     , X.NICKNAME
     , X.PRICE AS TOTAL_SALES
  FROM (
SELECT SUM(A.PRICE)   AS PRICE
     , MAX(B.USER_ID) AS USER_ID
     , MAX(B.NICKNAME) AS NICKNAME
  FROM USED_GOODS_BOARD A
INNER JOIN USED_GOODS_USER B
    ON A.WRITER_ID = B.USER_ID
WHERE A.STATUS = 'DONE'
GROUP BY A.WRITER_ID
      ) X
     WHERE X.PRICE >= 700000
    ORDER BY X.PRICE
     
 