
SELECT A.MEMBER_NAME
     , C.REVIEW_TEXT
     , DATE_FORMAT(C.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
  FROM MEMBER_PROFILE A
   INNER JOIN (
            SELECT MEMBER_ID
                  , ROW_NUMBER() OVER(ORDER BY COUNT(1) DESC) AS RNUM
               FROM REST_REVIEW
            GROUP BY MEMBER_ID
        ) B
    ON A.MEMBER_ID = B.MEMBER_ID
INNER JOIN REST_REVIEW C
    ON A.MEMBER_ID = C.MEMBER_ID
 WHERE B.RNUM = 1
 ORDER BY C.REVIEW_DATE, C.REVIEW_TEXT