SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY
  FROM ITEM_INFO A
  INNER JOIN (
SELECT B.ITEM_ID
  FROM ITEM_INFO A
 INNER JOIN ITEM_TREE B
    ON A.ITEM_ID = B.PARENT_ITEM_ID
 WHERE A.RARITY = 'RARE'
      ) X
    ON A.ITEM_ID = X.ITEM_ID
    ORDER BY A.ITEM_ID DESC