
SELECT A.ID
     , A.GENOTYPE
     , A.PARENT_GENOTYPE
  FROM (
SELECT B.ID
     , CASE WHEN A.GENOTYPE & B.GENOTYPE = A.GENOTYPE THEN TRUE ELSE FALSE END AS T
     , A.GENOTYPE AS PARENT_GENOTYPE
     , B.GENOTYPE
  FROM ECOLI_DATA A
  INNER JOIN ECOLI_DATA B
    ON A.ID = B.PARENT_ID
      ) A
     WHERE A.T = 1