SELECT MONTH(Y.START_DATE) AS MONTH
     , Y.CAR_ID
     , COUNT(1) AS RECORDS
  FROM (
SELECT CAR_ID
     , COUNT(1) AS CNT
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
 WHERE MONTH(START_DATE) IN ('8', '9', '10')
   AND YEAR(START_DATE) = '2022'
  GROUP BY CAR_ID
  HAVING COUNT(1) >= 5
      ) X
     INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY Y
        ON Y.CAR_ID = X.CAR_ID
      WHERE MONTH(Y.START_DATE) IN ('8', '9', '10')
        AND YEAR(Y.START_DATE) = '2022'
  GROUP BY MONTH(Y.START_DATE), Y.CAR_ID
     ORDER BY 1, 2 DESC