SELECT COUNT(1) AS FISH_COUNT
     , X.MON AS MONTH
  FROM (
select ID
     , FISH_TYPE
     , IFNULL(LENGTH, 10) AS LENGTH
     , MONTH(TIME) AS MON
  from FISH_INFO 
  ) X
  GROUP BY X.MON
  ORDER BY X.MON