SELECT X.ID
     , X.EMAIL
     , X.FIRST_NAME
     , X.LAST_NAME
  FROM (
SELECT A.ID
     , A.FIRST_NAME
     , A.EMAIL
     , A.LAST_NAME
     , CASE WHEN A.SKILL_CODE & B.CODE = B.CODE THEN 'IN' ELSE 'OUT' END AS SKILL
     , B.NAME AS SKILL_NAME
  FROM DEVELOPERS A
 INNER JOIN SKILLCODES B
 WHERE B.NAME IN ('Python', 'C#')
  ) X
  WHERE X.SKILL = 'IN'
  GROUP BY X.ID, X.EMAIL, X.FIRST_NAME, X.LAST_NAME
 ORDER BY X.ID
 