
SELECT B.YEAR
     , B.SIZE - A.SIZE_OF_COLONY AS YEAR_DEV
     , A.ID
  FROM ECOLI_DATA A
INNER JOIN (
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR
     , MAX(SIZE_OF_COLONY) AS SIZE
  FROM ECOLI_DATA
 GROUP BY YEAR(DIFFERENTIATION_DATE)
    ) B
    ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY B.YEAR , B.SIZE - A.SIZE_OF_COLONY
 