SELECT  SUM(X.FISH_COUNT) AS FISH_COUNT
  FROM (
select COUNT(1) AS FISH_COUNT
  from FISH_INFO  A
  INNER JOIN FISH_NAME_INFO  B
   ON A.FISH_TYPE = B.FISH_TYPE
 where B.FISH_NAME IN ('BASS', 'SNAPPER')
 GROUP BY A.FISH_TYPE
      ) X