SELECT T.ID
     , X.FISH_NAME
     , X.LENGTH
  FROM FISH_INFO T
 INNER JOIN (
select MAX(B.FISH_NAME) AS FISH_NAME
     , A.FISH_TYPE
     , MAX(IFNULL(A.LENGTH, 10)) AS LENGTH
  from FISH_INFO A
    INNER JOIN  FISH_NAME_INFO B
      ON A.FISH_TYPE = B.FISH_TYPE
 group by A.FISH_TYPE
     ) X
  ON T.FISH_TYPE = X.FISH_TYPE
 AND T.LENGTH = X.LENGTH
 ORDER BY T.ID