SELECT B.SCORE
     , A.EMP_NO
     , A.EMP_NAME
     , A.POSITION
     , A.EMAIL
  FROM HR_EMPLOYEES A
INNER JOIN (
SELECT EMP_NO
     , SUM(SCORE) AS SCORE
     , RANK() OVER (ORDER BY SUM(SCORE) DESC) AS O_RANK
  FROM HR_GRADE 
 WHERE YEAR = '2022'
 GROUP BY EMP_NO, YEAR
    ) B
WHERE A.EMP_NO = B.EMP_NO
  AND B.O_RANK = 1