SELECT X.FISH_COUNT
     , X.MAX_LENGTH
     , X.FISH_TYPE
  FROM (
SELECT A.FISH_TYPE
     , AVG(A.LENGTH) AS AVG_LENGTH
     , COUNT(A.ID) AS FISH_COUNT
     , MAX(A.LENGTH) AS MAX_LENGTH
  FROM (
       SELECT ID, FISH_TYPE, IFNULL(LENGTH, 10) AS LENGTH
        FROM FISH_INFO
       ) A
 GROUP BY A.FISH_TYPE
      )  X
     WHERE X.AVG_LENGTH >= 33
    ORDER BY X.FISH_TYPE